workflows:
  build_ios:
    name: Build iOS
    scripts:
      - npm install -g eas-cli
      - npm install
      - eas login --non-interactive --username nithinnv --password thestudent
      - eas build -p ios
    artifacts:
      - eas-build/**/*.ipa
