workflows:
  build_ios:
    name: Build iOS
    environment:
      EXPO_CLI_PASSWORD: thestudent
    scripts:
      - npm install -g eas-cli
      - npm install
      - eas login --username nithinnv --password thestudent
      - eas build -p ios
    artifacts:
      - eas-build/**/*.ipa
