workflows:
  build_ios:
    name: Build iOS
    scripts:
      - npm install -g eas-cli
      - npm install
      - echo -e "nithinnv\nthestudent" | eas login
      - eas build -p ios
    artifacts:
      - eas-build/**/*.ipa
