workflows:
  ios-build:
    name: iOS Build
    environment:
      react_native_version: 0.64.2

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Set up Expo credentials
        script: |
          echo "EXPO_USERNAME=<nithinnv>" >> $FCI_BUILD_DIR/.env
          echo "EXPO_PASSWORD=<thestudent>" >> $FCI_BUILD_DIR/.env

      - name: Build iOS app
        script: |
          eas build -p ios

      # Add more build steps as needed

    cache:
      key: v1-dependencies-{{ checksum "package-lock.json" }}-{{ checksum ".env" }}
      directories:
        - ~/.npm
