workflows:
  build_ios:
    name: Build iOS
    scripts:
      - npm install -g eas-cli
      - npm install
      - echo -e "machine api.expo.dev\n  login $nithin\n  password $thestudent" > $HOME/.netrc
      - eas build -p ios
    artifacts:
      - eas-build/**/*.ipa
