workflows:
  build_ios:
    name: Build iOS
    scripts:
      - npm install -g eas-cli
      - npm install
      - eas build -p ios --username="$EXPO_USERNAME" --password="$EXPO_PASSWORD"
    artifacts:
      - eas-build/**/*.ipa
